#???????????????????root????????demo????????????
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/woc?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true

#mybatis??resources?mapper?????xml??
mybatis:
  mapper-locations: classpath:mapper/*.xml

#???8081
server:
  port: 8081


